const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/multapplyDev');
var Listing = require('../models/listing');
//We require mongoose.
//We connect to the local host under jwt so the different users can access different seeds.
//We require the model, so the data is populated in the db.

//Set the Array of objects to a const.
const listingSeeder = [
  {
    title: 'quaint cottage',
    description: 'this country home has a great view',
    street: '31 Hermina Lane',
    city: 'Cleveland',
    state: 'Ohio',
    zip: '44197',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 2,
    bathrooms: 2.5,
    sqFeet: 1087,
    dogs: false,
    cats: true,
    otherPets: true,
  },
  {
    title: 'farm home',
    description: 'this barn doubles as a house',
    street: '26922 Tennyson Junction',
    city: 'Boise',
    state: 'Idaho',
    zip: '83732',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 1,
    bathrooms: 0.5,
    sqFeet: 500,
    dogs: true,
    cats: true,
    otherPets: true,
  },
  {
    title: 'sea view condo',
    description: 'this condo is right on the beach',
    street: '01851 Colorado Point',
    city: '	Amarillo',
    state: 'Texas',
    zip: '79159',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 3,
    bathrooms: 2,
    sqFeet: 1200,
    dogs: true,
    cats: false,
    otherPets: true,
  },
  {
    title: 'micro house',
    description: 'enough room for a bed and a suicase',
    street: '052 Marquette Center',
    city: 'Rochester',
    state: 'New York',
    zip: '14624',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 1,
    bathrooms: 1,
    sqFeet: 200,
    dogs: false,
    cats: false,
    otherPets: false,
  },
  {
    title: 'downtown house',
    description: 'this large house takes up a city blocks',
    street: '6886 Westerfield Trail',
    city: 'El Paso',
    state: 'Texas',
    zip: '88530',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 24,
    bathrooms: 31,
    sqFeet: 25000,
    dogs: true,
    cats: true,
    otherPets: true,
  },
  {
    title: 'dog house',
    description: 'we have room in our backyard dog house',
    street: '60657 Maple Center',
    city: 'Englewood',
    state: 'Colorado',
    zip: '80150',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 0,
    bathrooms: 0,
    sqFeet: 20,
    dogs: true,
    cats: false,
    otherPets: false,
  },
  {
    title: 'row houses in the city',
    description: 'this row houses is rustic masterpiece with the original plubming intact',
    street: '2355 Knutson Hill',
    city: 'Wilkes Barre',
    state: 'Pennsylvania',
    zip: '18706',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 4,
    bedrooms: 2,
    bathrooms: 2.5,
    sqFeet: 2000,
    dogs: true,
    cats: true,
    otherPets: true,
  },
  {
    title: 'oasis in the desert',
    description: 'this house is litteraly in the middle of a desert',
    street: '09677 Maryland Way',
    city: 'North Las Vegas',
    state: 'Nevada',
    zip: '89087',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 8,
    bathrooms: 2.5,
    sqFeet: 3100,
    dogs: true,
    cats: true,
    otherPets: true,
  },
  {
    title: 'Parade Paradise',
    description: 'this residence is a broken Mardi Gras float',
    street: '15 Maple Wood Plaza',
    city: '	New Orleans',
    state: 'Louisiana',
    zip: '70183',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 1,
    bathrooms: 1,
    sqFeet: 50,
    dogs: false,
    cats: false,
    otherPets: false,
  },
  {
    title: 'largest home for rent in seattle',
    description: 'this is the largest home for rent in seattle',
    street: '111 4th Avenue',
    city: 'Seattle',
    state: 'Washington',
    zip: '98103',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 1,
    bathrooms: 1,
    sqFeet: 100,
    dogs: false,
    cats: false,
    otherPets: false,
  },
  {
    title: 'Clean house for rent',
    description: 'great house for rent',
    street: '414 Loomis Circle',
    city: 'Cleveland',
    state: 'Ohio',
    zip: '45192',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 5,
    bathrooms: 4,
    sqFeet: 2500,
    dogs: true,
    cats: true,
    otherPets: true,
  },
  {
    title: 'house for rent',
    description: 'find your next house here!',
    street: '21 Quelatin Lane',
    city: 'Paris',
    state: 'Texas',
    zip: '55197',
    available: true,
    dateAvailable: '7/4/2018',
    numUnits: 1,
    bedrooms: 3,
    bathrooms: 2,
    sqFeet: 1700,
    dogs: true,
    cats: true,
    otherPets: true,
  },


];

//Use the insertMany function to seed to the db.
//This must be run in node.
Listing.insertMany(listingSeeder, (err, docs) => {
  console.log(err);
  console.log(docs);
})
