const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/jwtAuth');
var User = require('../models/Users');
//We require mongoose.
//We connect to the local host under jwt so the different users can access different seeds.
//We require the model, so the data is populated in the db.

//Set the Array of objects to a const.
const restSeeds = [
  {
    name: 'Brody Sissons',
    email: 'bsissons0@virginia.edu',
    password: 'password',
    dateOfBirth: 2/2/1927,
    phone: 2698859825,
    street: '12191 Derek Crossing',
    city: 'Magsaysay',
    zip: 9221,
    prevAddresses: ,
    socialSecurity: 131724887,
    currentEmployer: 'Aufderhar, Beatty and Botsford',
    currentMonthIncome: 78199,
    creditScore: 	720,
    groupId: ,
    references: ,
    isPropertyManager: true,
    propertiesManaged: ,
  },
  {
    name: 'Siana Weiser',
    email: 'sweiser1@qq.com',
    password: 'password',
    dateOfBirth: 1/7/1920,
    phone: 5418384486,
    street: '0 Dawn Court',
    city: 'Taourirt',
    zip: 9331,
    prevAddresses: ,
    socialSecurity: 352772119,
    currentEmployer: 'Luettgen, Robel and Borer',
    currentMonthIncome: 25753,
    creditScore: 	596,
    groupId: ,
    references: ,
    isPropertyManager: true,
    propertiesManaged: ,
  },
  {
    name: 'Morgan Earland',
    email: 'mearland2@histats.com',
    password: 'password',
    dateOfBirth: 	12/10/1929,
    phone: 	4702768363,
    street: '4509 Muir Place',
    city: 'Taourirt',
    zip: 9241,
    prevAddresses: ,
    socialSecurity: 281105413,
    currentEmployer: 'Little-Harris',
    currentMonthIncome: 16260,
    creditScore: 	580,
    groupId: ,
    references: ,
    isPropertyManager: false,
    propertiesManaged: ,
  },
  {
    name: 'Dugald Sibley',
    email: 'dsibley3@tamu.edu',
    password: 'password',
    dateOfBirth: 	11/1/1912,
    phone: 	6919194035,
    street: '52052 2nd Way',
    city: 'Sulbiny Górne',
    zip: 08420,
    prevAddresses: ,
    socialSecurity: 260045197,
    currentEmployer: 'Stokes, Bergstrom and Boyer',
    currentMonthIncome: 19667,
    creditScore: 771,
    groupId: ,
    references: ,
    isPropertyManager: false,
    propertiesManaged: ,
  },
  {
    name: 'Heddi Frisby',
    email: 'hfrisby4@list-manage.com',
    password: 'password',
    dateOfBirth: 	8/15/1904,
    phone: 	9717303369,
    street: '1160 Lillian Crossing',
    city: 'Muyinga',
    zip: 08380,
    prevAddresses: ,
    socialSecurity: 149095479,
    currentEmployer: 'Schulist-Conroy',
    currentMonthIncome: 17513,
    creditScore: 452,
    groupId: ,
    references: ,
    isPropertyManager: false,
    propertiesManaged: ,
  },
  {
    name: 'Zelig Brader',
    email: 'zbrader5@squarespace.com',
    password: 'password',
    dateOfBirth: 	8/25/2006,
    phone: 	5246268868,
    street: '120 Moland Crossing',
    city: 'San Antonio',
    zip: 72089,
    prevAddresses: ,
    socialSecurity: 226868992,
    currentEmployer: 'Jacobi, Lemke and Paucek',
    currentMonthIncome: 99357,
    creditScore: 640,
    groupId: ,
    references: ,
    isPropertyManager: false,
    propertiesManaged: ,
  },
  {
    name: 'Zelig Brader',
    email: 'zbrader5@squarespace.com',
    password: 'password',
    dateOfBirth: 	8/25/2006,
    phone: 	5246268868,
    street: '120 Moland Crossing',
    city: 'San Antonio',
    zip: 72089,
    prevAddresses: ,
    socialSecurity: 226868992,
    currentEmployer: 'Jacobi, Lemke and Paucek',
    currentMonthIncome: 99357,
    creditScore: 640,
    groupId: ,
    references: ,
    isPropertyManager: false,
    propertiesManaged: ,
  },
];

//Use the insertMany function to seed to the db.
//This must be run in node.
Restaurant.insertMany(restSeeds, (err, docs) => {
  console.log(err);
  console.log(docs);
})
